 const countryList = [
     "Afghanistan",
     "Albania",
     "Algeria",
     "Andorra",
     "Angola",
     "Antigua and Barbuda",
     "Argentina",
     "Armenia",
     "Australia",
     "Austria",
     "Azerbaijan",
     "Bahamas",
     "Bahrain",
     "Bangladesh",
     "Barbados",
     "Belarus",
     "Belgium",
     "Belize",
     "Benin",
     "Bermuda",
     "Bhutan",
     "Bolivia (Plurinational State of)",
     "Bosnia and Herzegovina",
     "Botswana",
     "Brazil",
     "Brunei Darussalam",
     "Bulgaria",
     "Burkina Faso",
     "Burundi",
     "Cambodia",
     "Cameroon",
     "Canada",
     "Cape Verde",
     "Cayman Islands",
     "Central African Republic",
     "Chad",
     "Chile",
     "China",
     "Colombia",
     "Congo, the Democratic Republic of the",
     "Congo",
     "Costa Rica",
     "Cote d'Ivoire",
     "Croatia",
     "Cuba",
     "Cyprus",
     "Czech Republic",
     "Denmark",
     "Djibouti",
     "Dominica",
     "Dominican Republic",
     "Ecuador",
     "Egypt",
     "El Salvador",
     "Equatorial Guinea",
     "Eritrea",
     "Estonia",
     "Ethiopia",
     "Faroe Islands",
     "Fiji",
     "Finland",
     "France",
     "French Guiana",
     "French Polynesia",
     "Gabon",
     "Gambia",
     "Georgia",
     "Germany",
     "Ghana",
     "Greece",
     "Greenland",
     "Grenada",
     "Guadeloupe",
     "Guam",
     "Guatemala",
     "Guernsey",
     "Guinea",
     "Guyana",
     "Haiti",
     "Heard Island and McDonald Islands",
     "Holy See",
     "Honduras",
     "Hong Kong",
     "Hungary",
     "Iceland",
     "India",
     "Indonesia",
     "Iran",
     "Iraq",
     "Ireland",
     "Israel",
     "Italy",
     "Jamaica",
     "Japan",
     "Jordan",
     "Kazakhstan",
     "Kenya",
     "Kiribati",
     "Korea, the Democratic People's Republic of",
     "Korea, the Republic of",
     "Kosovo",
     "Kuwait",
     "Kyrgyzstan",
     "Lao People's Democratic Republic",
     "Latvia",
     "Lebanon",
     "Lesotho",
     "Liberia",
     "Libya",
     "Liechtenstein",
     "Lithuania",
     "Luxembourg",
     "Macao",
     "Madagascar",
     "Malawi",
     "Malaysia",
     "Maldives",
     "Mali",
     "Malta",
     "Martinique",
     "Mauritania",
     "Mauritius",
     "Mayotte",
     "Mexico",
     "Moldova, Republic of",
     "Monaco",
     "Mongolia",
     "Montenegro",
     "Montserrat",
     "Morocco",
     "Mozambique",
     "Myanmar",
     "Namibia",
     "Nepal",
     "Netherlands",
     "New Caledonia",
     "New Zealand",
     "Nicaragua",
     "Niger",
     "Nigeria",
     "Niue",
     "North Macedonia",
     "Norway",
     "Oman",
     "Pakistan",
     "Palestine, State of",
     "Panama",
     "Papua New Guinea",
     "Paraguay",
     "Peru",
     "Philippines",
     "Poland",
     "Portugal",
     "Puerto Rico",
     "Qatar",
     "Réunion",
     "Romania",
     "Russian Federation",
     "Rwanda",
     "Saint Kitts and Nevis",
     "Saint Lucia",
     "Saint Vincent and the Grenadines",
     "Samoa",
     "San Marino",
     "Saudi Arabia",
     "Senegal",
     "Serbia",
     "Seychelles",
     "Sierra Leone",
     "Singapore",
     "Sint Maarten (Dutch part)",
     "Slovakia",
     "Slovenia",
     "Solomon Islands",
     "Somalia",
     "South Africa",
     "South Sudan",
     "Spain",
     "Sri Lanka",
     "Sudan",
     "Suriname",
     "Swaziland",
     "Sweden",
     "Switzerland",
     "Syrian Arab Republic",
     "Taiwan",
     "Tajikistan",
     "Tanzania, United Republic of",
     "Thailand",
     "Timor-Leste",
     "Togo",
     "Tonga",
     "Trinidad and Tobago",
     "Tunisia",
     "Turkey",
     "Turkmenistan",
     "Turks and Caicos Islands",
     "Uganda",
     "Ukraine",
     "United Arab Emirates",
     "United Kingdom",
     "United States",
     "Uruguay",
     "Uzbekistan",
     "Venezuela",
     "Viet Nam",
     "Virgin Islands, British",
     "Yemen",
     "Zambia",
     "Zimbabwe",
 ];
 export { countryList }